---
threescale_deploy_template: "https://raw.githubusercontent.com/3scale/3scale-amp-openshift-templates/2.0.0.GA-redhat-2/apicast-gateway/apicast.yml"
threescale_image: "quay.io/3scale/apicast:master"
threescale_basic_auth_secret_name: "apicast-configuration-url-secret"
threescale_port: "8080"
threescale_redis_name: "redis-3scale"
threescale_apicast_cors: "https://raw.githubusercontent.com/3scale/apicast/master/examples/cors/cors.lua"
threescale_apicast_cors_config: "https://raw.githubusercontent.com/3scale/apicast/master/examples/cors/cors.conf"
